version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.7.4-browsers
        environment:
          MIX_ENV: test
          AWS_ACCESS_KEY_ID: access-key-id
          AWS_SECRET_ACCESS_KEY: secret-access-key
          AWS_REGION: some-s3-region
          AWS_S3_BUCKET: s3-bucket
          CACHE_SUFFIX: 0
    working_directory: ~/app

    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      - type: shell
        name: "Write CACHE_SUFFIX to file"
        command: echo "$CACHE_SUFFIX" > ~/cache_suffix.txt

      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}-{{ checksum "~/cache_suffix.txt" }}
            - v1-mix-cache-{{ .Branch }}-{{ checksum "~/cache_suffix.txt" }}
            - v1-mix-cache-{{ checksum "~/cache_suffix.txt" }}
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}-{{ checksum "~/cache_suffix.txt" }}
            - v1-build-cache-{{ checksum "~/cache_suffix.txt" }}
      - run: mix do deps.get, compile
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}-{{ checksum "~/cache_suffix.txt" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "~/cache_suffix.txt" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache-{{ checksum "~/cache_suffix.txt" }}
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}-{{ checksum "~/cache_suffix.txt" }}
          paths: "_build"
      - save_cache:
          key: v1-build-cache-{{ checksum "~/cache_suffix.txt" }}
          paths: "_build"

      - run: mix test

      - store_test_results:
          path: _build/test/lib/hello_phoenix
